### ISSUE TITLE
seperate generation of spicedecks and running sims to save time

### ISSUE THREAD

**Issue by saicharan0112** [idea-fasoc/OpenFASOC-sims#1]
Currently the workflow just does everything (from running the generator to running simulations). For Xyce, it didn't took much time (6 hours) to run prePEX and postPEX is completely failing for some reason. Ngspice is able to generate data at Xyce failing points (temps and configs). 

The idea is modify the workflow (./.github/workflows/tempSense_sky130hd.yml) so that first the generator creates the spicedecks and stores them in /home/$USER/runner_results location on the runner GCP machine. Then all sims (except -20c point) is ran in parallel. Later all -20c are ran in parallel. Later, the workflow continues in the old way itself. 
The idea is to save sim time and the proposed method is an experiment.

**Comment by saicharan0112** [comment]
commit numbers implementing this - 
* 46d47c3574d0c39e7e6c16375073fbf609b5d0ee
* 100491aacb47d17a912454dfdf90bef929fbabd8
* 1ef407d640fbe935014fd7f5d23192f66cd93c55
* 866cf16eb6cef361cd7178f903748fcbfcd1fa91 (last commit to test this workflow)

**Comment by msaligane** [comment]
Thanks @saicharan0112 
Have you tried informing the Xyce people about this mismatch?

**Comment by saicharan0112** [comment]
No. I was thinking to add ngspice results to this repo first before sharing
the issue with Xyce folks. Will try to do that today.

**Comment by saicharan0112** [comment]
The parallel workflow is now available.
